// server.js — Claude Manager v2
// Run: node server.js  |  Open: http://localhost:3847

const http = require('http');
const fs   = require('fs');
const path = require('path');

const PORT     = 3847;
const ROOT     = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const UI_DIR   = path.join(ROOT, 'ui');
const CLAUDE_MD   = path.join(ROOT, 'CLAUDE.md');
const BACKUPS_DIR = path.join(DATA_DIR, 'backups');
const SESSION_LOG = path.join(DATA_DIR, 'session-log.json');
const MODES_FILE  = path.join(DATA_DIR, 'modes.json');

const MIME = {
  '.html': 'text/html', '.js': 'application/javascript',
  '.css': 'text/css',   '.json': 'application/json',
};

const readData = f => { try { return JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8')); } catch { return null; } };
const writeData = (f, d) => fs.writeFileSync(path.join(DATA_DIR, f), JSON.stringify(d, null, 2), 'utf8');

function cors(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}
function body(req) {
  return new Promise(r => {
    let d = '';
    req.on('data', c => d += c);
    req.on('end', () => { try { r(JSON.parse(d)); } catch { r({}); } });
  });
}
function json(res, data, status = 200) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}

const SKILL_MAP = {
  'example-skill': { cat: 'Examples', path: path.join(ROOT, 'skills', 'example-skill', 'SKILL.md') }
};

function regenerateCLAUDEmd() {
  const states = readData('skill-states.json') || {};
  const stateMap = states.states || states;
  const activeSkills = Object.entries(SKILL_MAP).filter(([id]) => stateMap[id] !== false);
  const skillTable = activeSkills.map(([,s]) => `| ${s.cat.padEnd(28)} | ${s.path} |`).join('\n');
  const activeCount = activeSkills.length;
  const total = Object.keys(SKILL_MAP).length;
  const now = new Date().toISOString().split('T')[0];
  const content = `# Claude Context
> Auto-loaded by Claude Code. Last updated: ${now}.
> Active skills: ${activeCount}/${total}. Regenerated by Claude Manager.

---

## Data Files (read at session start)
| File | Purpose |
|------|---------|
| data/memory.json | Built memory |
| data/rules.json | Operational rules |
| data/skill-states.json| Which skills are active/inactive |

---

## Active Skills (${activeCount}/${total})
Before any task, check if a matching skill is active, then read its SKILL.md.

| Task type                     | Skill file |
|-------------------------------|------------|
${skillTable}
`;
  fs.writeFileSync(CLAUDE_MD, content, 'utf8');
  return { activeCount, total };
}

function skillHealthCheck() {
  return Object.entries(SKILL_MAP).map(([id, s]) => {
    const exists = fs.existsSync(s.path);
    return { id, path: s.path, exists, issue: exists ? null : 'SKILL.md not found' };
  });
}

function createBackup() {
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const dir = path.join(BACKUPS_DIR, ts);
  fs.mkdirSync(dir, { recursive: true });
  ['memory.json', 'rules.json', 'skill-states.json'].forEach(f => {
    const src = path.join(DATA_DIR, f);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(dir, f));
  });
  if (fs.existsSync(CLAUDE_MD)) fs.copyFileSync(CLAUDE_MD, path.join(dir, 'CLAUDE.md'));
  return { timestamp: ts };
}
function listBackups() {
  if (!fs.existsSync(BACKUPS_DIR)) return [];
  return fs.readdirSync(BACKUPS_DIR)
    .filter(d => fs.statSync(path.join(BACKUPS_DIR, d)).isDirectory())
    .sort().reverse().slice(0, 20).map(ts => ({ timestamp: ts }));
}
function restoreBackup(ts) {
  const dir = path.join(BACKUPS_DIR, ts);
  if (!fs.existsSync(dir)) return false;
  ['memory.json', 'rules.json', 'skill-states.json'].forEach(f => {
    const src = path.join(dir, f);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(DATA_DIR, f));
  });
  const cm = path.join(dir, 'CLAUDE.md');
  if (fs.existsSync(cm)) fs.copyFileSync(cm, CLAUDE_MD);
  return true;
}

function getSessionLog() {
  try { return JSON.parse(fs.readFileSync(SESSION_LOG, 'utf8')); }
  catch { return { sessions: [] }; }
}
function appendSession(entry) {
  const log = getSessionLog();
  log.sessions.unshift({ ...entry, ts: new Date().toISOString() });
  log.sessions = log.sessions.slice(0, 50);
  fs.writeFileSync(SESSION_LOG, JSON.stringify(log, null, 2), 'utf8');
}

function estimateContextBudget() {
  try {
    const claudeMd  = fs.existsSync(CLAUDE_MD) ? fs.readFileSync(CLAUDE_MD, 'utf8') : '';
    const memText   = JSON.stringify(readData('memory.json') || '');
    const rulesText = JSON.stringify(readData('rules.json') || '');
    const totalChars = claudeMd.length + memText.length + rulesText.length;
    const estimatedTokens = Math.round(totalChars / 4);
    return {
      claudeMdChars: claudeMd.length, memoryChars: memText.length,
      rulesChars: rulesText.length, totalChars,
      estimatedTokens, budgetPercent: Math.round((estimatedTokens / 200000) * 100),
      claudeMdLines: claudeMd.split('\n').length
    };
  } catch(e) { return { error: e.message }; }
}

// ---- Modes — icon is now a string key, rendered as SVG in the UI ----
const DEFAULT_MODES = {
  modes: [
    {
      id: 'all', label: 'All On', icon: 'unlock',
      desc: 'Activate all skills.',
      skills: Object.keys(SKILL_MAP)
    }
  ]
};

function getModes() {
  try { return JSON.parse(fs.readFileSync(MODES_FILE, 'utf8')); }
  catch { return DEFAULT_MODES; }
}

function applyMode(modeId) {
  const modesData = getModes();
  const mode = modesData.modes.find(m => m.id === modeId);
  if (!mode) return null;
  const states = readData('skill-states.json') || {};
  const stateMap = states.states || {};
  Object.keys(SKILL_MAP).forEach(id => { stateMap[id] = false; });
  mode.skills.forEach(id => { stateMap[id] = true; });
  const newStates = { version: '1.0', last_updated: new Date().toISOString().split('T')[0], states: stateMap };
  writeData('skill-states.json', newStates);
  regenerateCLAUDEmd();
  appendSession({ type: 'mode_applied', mode: modeId, skills: mode.skills });
  return newStates;
}

const server = http.createServer(async (req, res) => {
  cors(res);
  if (req.method === 'OPTIONS') { res.writeHead(204); return res.end(); }
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const p = url.pathname;

  if (p === '/api/memory'  && req.method === 'GET')  return json(res, readData('memory.json'));
  if (p === '/api/memory'  && req.method === 'POST')  { writeData('memory.json', await body(req)); return json(res, {ok:true}); }
  if (p === '/api/rules'   && req.method === 'GET')   return json(res, readData('rules.json'));
  if (p === '/api/rules'   && req.method === 'POST')  { writeData('rules.json', await body(req)); return json(res, {ok:true}); }
  if (p === '/api/states'  && req.method === 'GET')   return json(res, readData('skill-states.json'));
  if (p === '/api/states'  && req.method === 'POST')  {
    const data = await body(req);
    writeData('skill-states.json', data);
    const regen = regenerateCLAUDEmd();
    appendSession({ type: 'toggle', activeSkills: regen.activeCount });
    return json(res, { ok: true, ...regen });
  }
  if (p === '/api/claude-md' && req.method === 'GET') {
    try { return json(res, { content: fs.readFileSync(CLAUDE_MD, 'utf8'), ...estimateContextBudget() }); }
    catch { return json(res, { content: '', error: 'File not found' }); }
  }
  if (p === '/api/claude-md' && req.method === 'POST') {
    const r = regenerateCLAUDEmd();
    appendSession({ type: 'manual_regen', ...r });
    return json(res, { ok: true, ...r });
  }
  if (p === '/api/health'   && req.method === 'GET') return json(res, { skills: skillHealthCheck(), budget: estimateContextBudget() });
  if (p === '/api/backups'  && req.method === 'GET') return json(res, { backups: listBackups() });
  if (p === '/api/backups'  && req.method === 'POST') {
    const b = createBackup();
    appendSession({ type: 'backup', timestamp: b.timestamp });
    return json(res, { ok: true, ...b });
  }
  if (p === '/api/restore'  && req.method === 'POST') {
    const { timestamp } = await body(req);
    const ok = restoreBackup(timestamp);
    if (ok) regenerateCLAUDEmd();
    return json(res, { ok });
  }
  if (p === '/api/session-log' && req.method === 'GET')  return json(res, getSessionLog());
  if (p === '/api/session-log' && req.method === 'POST') { appendSession(await body(req)); return json(res, {ok:true}); }
  if (p === '/api/modes'       && req.method === 'GET')  return json(res, getModes());
  if (p === '/api/modes/apply' && req.method === 'POST') {
    const { modeId } = await body(req);
    const result = applyMode(modeId);
    return result ? json(res, { ok: true, states: result }) : json(res, { ok: false, error: 'Mode not found' }, 404);
  }

  let filePath = path.join(UI_DIR, p === '/' ? '/index.html' : p);
  if (fs.existsSync(filePath)) {
    res.writeHead(200, { 'Content-Type': MIME[path.extname(filePath)] || 'text/plain' });
    return res.end(fs.readFileSync(filePath));
  }
  res.writeHead(404); res.end('Not found');
});

server.listen(PORT, () => {
  console.log(`Claude Manager v2 — http://localhost:${PORT}`);
  try {
    const r = regenerateCLAUDEmd();
    console.log(`CLAUDE.md regenerated — ${r.activeCount}/${r.total} skills active`);
  } catch(e) { console.error('CLAUDE.md regen failed:', e.message); }
});
